package com.cdasanpedro.core.model.enums;

public enum TipoCertificacion {
    INSPECTOR_LINEA_LIVIANOS,
    INSPECTOR_LINEA_PESADOS,
    INSPECTOR_LINEA_MOTOS,
    DIRECTOR_TECNICO,
    DIRECTOR_TECNICO_SUPLENTE,
    DIRECTOR_TECNICO_ISO17020,
    INSPECTOR_RTM_LIVIANOS,
    INSPECTOR_RTM_MOTOS,
    INSPECTOR_RTM_PESADOS,
    CALIBRACION_EQUIPOS,
    SEGURIDAD_SALUD_TRABAJO,
    PRIMEROS_AUXILIOS,
    SST_TRABAJO_ALTURAS,
    COMPETENCIA_LABORAL_SENA,
    OTRO,
    OTRA
}

